<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Olster cupcakes</title>
    <style>
        .pic{
            width: 100%;
            height: auto;
        }

    </style>
     </head>
<body>
<div> <img src="olskercupcakes.png" class="pic"> </div>
    <div style="background-color: #c6c8d1; width: 100%; height: 50px; margin-top: 10px">

        <a style="margin-left: 20px;" href="ordrerpage.asp">Ordrer</a> &nbsp;
        <a href="ordrerpage.asp">Kunder</a> &nbsp;
        <a href="ordrerpage.asp">email@email.dk </a>


        <a href="https://www.w3schools.com/%22%3E
            <img border="0" alt="Kurv" src="basket.png" width="40" height="40" align="right" style="margin-right: 10px">

    </div>
</div>
</body>
</html>